// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/cloudevents/sdk-go/v2/event"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, in
func (_m *Handler) Handle(ctx context.Context, in event.Event) (*event.Event, error) {
	ret := _m.Called(ctx, in)

	var r0 *event.Event
	if rf, ok := ret.Get(0).(func(context.Context, event.Event) *event.Event); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, event.Event) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
