// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	v2 "github.com/cloudevents/sdk-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// mock is an autogenerated mock type for the mock type
type Event struct {
	mock.Mock
}

// Publish provides a mock function with given fields: _a0, _a1
func (_m *Event) Publish(_a0 context.Context, _a1 []*v2.Event) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*v2.Event) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
